server:
  port: 9000
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 27fdbd2cd444e3a6acf9
            clientSecret: bf6c26ae4fc57f9504b30593d8521c95b31ba28c
            redirectUri: http://localhost/api/login/oauth2/code/github

logging:
  level:
    org.springframework.security: debug

